import type { Metadata } from 'next'
import { Jost } from 'next/font/google';
import './globals.css';
import MobileHeader from '../_components/mobile-header';
import ActionBar from '../_components/action-bar';

const font = Jost({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={font.className}>
      <MobileHeader/>
      <ActionBar/>
        {children}
        </body>
    </html>
  );
}
