import clsx from 'clsx';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';

import '@/app/(routes)/globals.css';
import RoadMapHeader from '@/app/_components/road-map-header';

const font = Jost({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          ' w-screen overflow-x-hidden bg-light-grey tablet:px-10 tablet:pt-14',
          font.className
        )}
      >
        <RoadMapHeader />
        <main className='mt-11 flex h-full w-full flex-col px-6 tablet:mt-0 tablet:px-0 '>
          {children}
        </main>
      </body>
    </html>
  );
}
